### GET users
GET {{host}}/api/auth/users


### GET users with filters
GET {{host}}/api/auth/users?filters={"field":"fullName","operator":"equal","value":"John Doe"}


### GET users with sort
GET {{host}}/api/auth/users?sort=[{"field":"email","direction":"asc"}]

### GET users with pagination
GET {{host}}/api/auth/users?skip=1&limit=3


### POST create user
POST {{host}}/api/auth/users
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john.doe3@tmp.com",
  "password": "password123"
}